# Site settings
course_name: "Assistência Remota para Microcomputadores"
course_description: "Disciplina de Assistência Remota para Microcomputadores do curso técnico subsequente de Manutenção e Suporte em Informática do IFB, campus Taguatinga."
course_semester: "2024/1"
baseurl: "/assistencia-remota-para-microcomputadores"
url: "https://danielsaad.com" # the base hostname & protocol for your site

schoolname: "Instituto Federal de Educação, Ciência e Tecnologia de Brasília, campus Taguatinga"
schoolurl: "https://www.ifb.edu.br/"
# twitter_username: username 

address: |
    Taguatinga
    IFB

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
